"""Add USCity table

Revision ID: 07091fc1aeda
Revises: 77a7b6458412
Create Date: 2025-05-07 13:24:57.993476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07091fc1aeda'
down_revision: Union[str, None] = '77a7b6458412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_cities_city'), 'us_cities', ['city'], unique=False)
    op.create_index(op.f('ix_us_cities_id'), 'us_cities', ['id'], unique=False)
    op.create_index(op.f('ix_us_cities_state_id'), 'us_cities', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_us_cities_state_id'), table_name='us_cities')
    op.drop_index(op.f('ix_us_cities_id'), table_name='us_cities')
    op.drop_index(op.f('ix_us_cities_city'), table_name='us_cities')
    op.drop_table('us_cities')
    # ### end Alembic commands ###
