"""Add Zip Codes Table

Revision ID: 77a7b6458412
Revises: 727741cae2ca
Create Date: 2025-05-03 22:00:46.261395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a7b6458412'
down_revision: Union[str, None] = '727741cae2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_codes_id'), 'zip_codes', ['id'], unique=False)
    op.create_index(op.f('ix_zip_codes_zip_code'), 'zip_codes', ['zip_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zip_codes_zip_code'), table_name='zip_codes')
    op.drop_index(op.f('ix_zip_codes_id'), table_name='zip_codes')
    op.drop_table('zip_codes')
    # ### end Alembic commands ###
