"""Add zip_code to us_cities

Revision ID: 9b307a638a45
Revises: 07091fc1aeda
Create Date: 2025-05-08 17:26:14.742476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b307a638a45'
down_revision: Union[str, None] = '07091fc1aeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_cities', sa.Column('zip_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('us_cities', 'zip_code')
    # ### end Alembic commands ###
